[build]
  publish = "."

[[headers]]
  for = "/repo.zip"
  [headers.values]
    Content-Type = "application/zip"
    Content-Disposition = "attachment; filename=\"repo.zip\""

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
